spring:
  application:
    name: Charichat
  datasource:
    url: jdbc:mysql://localhost:3306/charichat
    username: root
    password: window
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
